name: Build ASI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake (Win32, VS2022 stable toolset)
        run: cmake -B build -A Win32 -T v143

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Upload file .asi
        uses: actions/upload-artifact@v4
        with:
          name: WaypointRoute-asi
          path: build/Release/WaypointRoute.asi
